config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :journals
  resources :articles, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :journal
  has_many :users, through: :journal
  validates :name, presence: true
  validates :author, presence: true
  validates :doi, uniqueness: true
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :articles, dependent: :destroy
  validates :issn, uniqueness: true

  def self.refresh
    includes(:articles).find_each(&:refresh)
  end

  def refresh
    tries = 0
    new_articles = []
    backlog = true
    begin
      if articles.any?
        response = Serrano.journals(
          ids: issn,
          limit: 500,
          sort: 'published',
          works: true,
          order: 'desc',
          filter: { "from-pub-date" => (Date.yesterday - 1.day).to_s}
        )
        backlog = false
      else
        response = Serrano.journals(
          ids: issn,
          limit: 1000,
          sort: 'published',
          works: true,
          order: 'desc'
        )
      end
    rescue => e
      tries += 1
      Rails.logger.debug(e)
      retry if tries < 3
    end
    response.each do |journal_articles|
      journal_articles['message']['items'].each do |article|
        found = Article.find_by(doi: article['DOI'])
        unless found
          new_article = Article.create(
            date: article['created']['date-time'],
            journal: Journal.find_by(issn: article['ISSN']),
            author: article['author'] ? article['author'].map { |a| "#{a['family']}, #{a['given']}" }.to_sentence : nil,
            name: article['title']&.first,
            doi: article['DOI']
          )
          new_articles << new_article if new_article.persisted?
        end
      end
    end
    if new_articles.length > 0 && backlog == false
      users.each do |user|
        begin
          UserMailer.notify_new_issue(user, self, new_articles).deliver_now if user.issue_alerts
        rescue => e
          Rails.logger.debug e
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :journals
  has_many :articles, through: :journals

  def refresh_articles
    journals.each do |j|
      j.refresh
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:issue_alerts, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_for_journals

  def index
    @q = Article.ransack(params[:q])
    @q.sorts = 'date desc' if @q.sorts.empty?
    @articles = @q.result(distinct: true).includes(:journal, :users).where(users: { id: current_user.id }).page(params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    current_user.refresh_articles
    redirect_to articles_path
  end

  private

  def check_for_journals
    redirect_to new_journal_path if current_user.journals.empty?
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!

  def index
    @journals = current_user.journals.page(params[:page])
  end

  def destroy
    @journal = Journal.find(params[:id])
    current_user.journals.delete(@journal)
    redirect_to journals_path
  end

  def new
    if params[:journal] && params[:journal][:name]
      @journals = Serrano.journals(query: journal_params[:name])
    end
    @journal = Journal.new
  end

  def create
    @journal = Journal.find_or_create_by(journal_params)
    unless current_user.journals.include?(@journal)
      current_user.journals << @journal
    end
    redirect_to journals_path
  end

  private

  def journal_params
    params.require(:journal).permit(:issn, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
.float-right
  = search_form_for @q, class: 'form-inline' do |f|
    = f.search_field :author_cont, class: 'form-control mr-3', placeholder: 'Author'
    = f.search_field :journal_name_cont, class: 'form-control mr-3', placeholder: 'Journal'
    = f.submit "Search", class: 'btn btn-dark'
= content_tag :table do
  = content_tag :th, "Sort by:"
  = content_tag :th, sort_link(@q, :date)
  = content_tag :th, sort_link(@q, :author)
  = content_tag :th, sort_link(@q, :journals_name, "Journal")
%table.table.mt-5
  %thead
    %tr
      %td Date
      %td Author(s)
      %td Journal
      %td Title
      %td
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.date.strftime('%D')
        %td= article.author
        %td= article.journal.name
        %td= link_to article.name, "https://sci-hub.tw/#{article.doi}"
        %td
          .hide
            = article.doi
.float-left
  = paginate @articles, theme: 'twitter-bootstrap-4'
.float-right
  = link_to 'Refresh', articles_path, method: :post, class: 'btn btn-primary'
  %a{title: "Add this article to your Zotero library", href:"javascript:var d=document,s=d.createElement('script');s.src='https://www.zotero.org/bookmarklet/loader.js';(d.body?d.body:d.documentElement).appendChild(s);void(0);", class: 'btn btn-dark'}
    Save to Zotero

app/views/journals/index.html.haml
%h1 My Journal Subscriptions
= link_to 'Add a journal', new_journal_path, class: 'btn btn-dark mt-3'
%table.table.mt-5
  %tr
    %td Name
    %td
  - current_user.journals.each do |journal|
    %tr
      %td= journal.name
      %td= link_to 'Unsubscribe', journal_path(journal), method: :delete

app/views/journals/new.html.haml
%h1 Add a journal to your subscribing list

= form_for @journal, url: new_journal_path, method: :get do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit "Search", class: 'btn btn-dark'

- if @journals
  %table.table.mt-5
    %thead
      %tr
        %td Name
        %td
    %tbody
    - @journals['message']['items'].each do |result|
      %tr
        %td= result['title']
        %td
          = form_for Journal.new do |f|
            = f.hidden_field :name, value: result['title']
            = f.hidden_field :issn, value: result['ISSN'][0]
            = f.submit "Add", class: 'btn btn-sm btn-dark'
    - if @journals['message']['items'].empty?
      %tr
        %td No Results

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %link{:href => image_path("apple-touch-icon.png"), :rel => "apple-touch-icon", :sizes => "180x180"}/
    %link{:href => image_path("favicon-32x32.png"), :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %link{:href => image_path("favicon-16x16.png"), :rel => "icon", :sizes => "16x16", :type => "image/png"}/

    %title Journaled
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-md.navbar-light.bg-light.fixed-top
      %a.navbar-brand{:href => "/"} Journaled
      %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          = render 'devise/menu/registration_items'
          = render 'devise/menu/login_items'
    .container.mb-5
      .col-lg-12.mt-5.pt-5
        = yield